### ISSUE TITLE
Unhandled exception in internal background task `clear_reminders_backlog`

### ISSUE THREAD

**Issue by codemicro** [CSSUoB/TeX-Bot-Py-V2#119]
```
Unhandled exception in internal background task 'clear_reminders_backlog'.
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/app/cogs/remind_me.py", line 286, in clear_reminders_backlog
    async for reminder in DiscordReminder.objects.all():
  File "/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 405, in generator
    await sync_to_async(self._fetch_all)()
  File "/app/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 122, in __iter__
    obj = model_cls.from_db(
          ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 582, in from_db
    new = cls(*values)
          ^^^^^^^^^^^^
TypeError: AsyncBaseModel.__init__() takes 1 positional argument but 7 were given
```

**Comment by CarrotManMatt** [comment]
I was too hasty in thinking that the Django DB models will only be initialised with kwargs. Turns out (as this stack trace shows) that there is some internal Django logic that initialises your model via positional args.
